apiVersion: v1
kind: Deployment
metadata:
  name: test-app-backend
spec:
  selector:
    matchLabels:
      app: test-app-backend
  template:
    metadata:
      labels:
        app: test-app-backend
    spec:
      containers:
      - name: test-app-backend
        image: test-app-backend:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: test-app-backend-01
            mountPath: /mnt/sd01 
      volumes:
        - name: test-app-backend-01
          persistentVolumeClaim:
            claimName: test-app-backend-pvc
