apiVersion: v1
kind: Service
metadata:
  name: test-app-backend
spec:
  selector:
    app: test-app-backend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-backend-worker
spec:
  selector:
    app: test-app-backend-worker
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-frontend
spec:
  selector:
    app: test-app-frontend
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
